=== aalm1233/AutoSystem-Test/resource/schema/XMLSchema11_24.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.w3school.com.cn" xmlns="http://www.w3school.com.cn"
	elementFormDefault="qualified">
	<xs:element name="resources">
		<xs:complexType mixed="true">
			<xs:all minOccurs="0">
				<xs:element name="add" type="operation" />
				<xs:element name="delete" type="operation" />
				<xs:element name="update" type="operation" />
				<xs:element name="find" type="operation" />
			</xs:all>
			<xs:attribute name="id" type="xs:string" use="required" />
			<xs:attribute name="name" type="xs:string" use="required" />
			<xs:attribute name="base" type="xs:string" use="required" />
			<xs:attribute name="permise" type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:complexType name="operation">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="resource">
				<xs:complexType mixed="true">
					<xs:sequence>
						<xs:element name="request">
							<xs:complexType>
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element name="dependecy">
										<xs:complexType>
											<xs:attribute name="resourcesid" type="xs:string" use="required" />
											<xs:attribute name="resourceid" type="xs:string" use="required" />
										</xs:complexType>
									</xs:element>
									<xs:element name="param">
										<xs:complexType>
											<xs:all minOccurs="0">
												<xs:element name="restriction" type="constraint"></xs:element>
												<xs:element name="element"><!-- 去掉了string类型修饰 -->
													<xs:complexType>
														<xs:attribute name="name" type="xs:string" />
														<xs:attribute name="level" type="xs:unsignedInt"></xs:attribute>
														<xs:attribute name="type" type="xs:string"
															use="required" />
													</xs:complexType>
												</xs:element>
											</xs:all>
											<xs:attribute name="name" type="xs:string" use="required" />
											<xs:attribute name="attribute" type="xs:string"
												use="required" />
											<xs:attribute name="type" type="xs:string" use="required" />
											<xs:attribute name="location" type="xs:boolean" use="required"/>
											<xs:attribute name="required" type="xs:boolean"
												default="true" />
										</xs:complexType>
									</xs:element><!--param元素 -->
								</xs:sequence>
							</xs:complexType>
						</xs:element><!--request元素 -->
						<xs:element name="response">
							<xs:complexType mixed="true">
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element name="param">
										<xs:complexType>
											<xs:attribute name="name" type="xs:string" use="required" />
											<xs:attribute name="attribute" type="xs:string"
												use="required" />
										</xs:complexType>
									</xs:element><!--param元素 -->
								</xs:sequence>
								<xs:attribute name="name" type="xs:string" use="required" />
								<xs:attribute name="dataType" type="xs:string" use="required" />
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="id" type="xs:string" use="required" />
					<xs:attribute name="name" type="xs:string" use="required" />
					<xs:attribute name="path" type="xs:string" use="required" />
					<xs:attribute name="cascade" type="xs:boolean"
						default="false" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="constraint">
		<xs:all minOccurs="0">
			<xs:element name="enumeration" type="xs:string" />
			<xs:element name="totalDigits" type="xs:integer" />
			<xs:element name="fractionDigit" type="xs:integer" />
			<xs:element name="minExclusive" type="xs:integer" />
			<xs:element name="maxExclusive" type="xs:integer" />
			<xs:element name="minInclusive" type="xs:integer" />
			<xs:element name="maxInclusive" type="xs:integer" />
			<xs:element name="length" type="xs:integer" />
			<xs:element name="minLength" type="xs:integer" />
			<xs:element name="maxLength" type="xs:integer" />
			<xs:element name="minDate" type="xs:date" />
			<xs:element name="maxDate" type="xs:date" />
			<xs:element name="pattern" type="xs:string" />
			<xs:element name="format" type="xs:string" />
			<xs:element name="minSize" type="xs:decimal" />
			<xs:element name="maxSize" type="xs:decimal" />
			<xs:element name="whiteSpace" type="xs:string" />
			<xs:element name="sensitive" type="xs:boolean" />
		</xs:all>
	</xs:complexType>
</xs:schema>

=== aalm1233/AutoSystem-Test/resource/inputxml/materialinfo.xml
<?xml version="1.0" encoding="UTF-8"?><resources base="http://" id="materialinformation_Service" name="MaterialinfoController" xmlns="http://www.w3school.com.cn" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3school.com.cn ../schema/XMLSchema11_24.xsd "><add><resource name="addMaterials" path="addMaterials" id="Material_New"><request><param name="imgTitle1" type="String" attribute="Materialinformation.imgTitle1"></param><param name="imgAuthor1" type="String" attribute="Materialinformation.imgAuthor1"></param><param name="imgDetail1" type="String" attribute="Materialinformation.imgDetail1"></param><param name="CommonsMultipartFile" type="imgFiles" attribute="Materialinformation.CommonsMultipartFile"></param></request><response dataType="JSON"><data name="" type="String"></data></response></resource></add><delete><resource name="deleteMultipleMaterials" path="deleteMultipleMaterials" id="Delete_MultipleMaterials"><request><param name="pictureName" type="String[]" attribute="Materialinformation.pictureName"></param></request><response dataType="JSON"><data name="" type="String"></data></response></resource><resource name="deleteMaterials" path="deleteMaterials" id="Delete_Materials"><request><param name="materialId" type="String" attribute="Materialinformation.materialId"></param></request><response dataType="JSON"><data name="" type="String"></data></response></resource></delete><update><resource name="editMaterialInfo" path="editMaterialInfo" id="UPDATE_MaterialInfo"><request><param name="materialId" type="String" attribute="Materialinformation.materialId"></param><param name="imgTitle1" type="String" attribute="Materialinformation.imgTitle1"></param><param name="imgAuthor1" type="String" attribute="Materialinformation.imgAuthor1"><restriction><enumeration >sdgsdf</enumeration></restriction></param><param name="imgDetail1" type="String" attribute="Materialinformation.imgDetail1"></param><param name="CommonsMultipartFile" type="imgFiles" attribute="Materialinformation.CommonsMultipartFile"></param></request><response dataType="JSON"><data name="" type="String"></data></response></resource></update><find><resource name="displaySellerInfo" path="displaySellerInfo" id="FIND_SellerInfo"><request></request><response dataType="JSON"><data name="" type="String"></data></response></resource><resource id="Materialinformation_Find_Condition" name="searchMaterial" path="searchMaterial"><request><param name="accessState" attribute="Materialinformation.state" type="String"></param><param name="phototype" attribute="Materialinformation.type" type="String"></param><param name="title" attribute="Materialinformation.title" type="String" /><param name="starttime" type="String" attribute="Materialinformation.starttime" /><param name="endtime" type="String" attribute="Materialinformation.endtime" /></request><response dataType="JSON"><data name="" type="String" /></response></resource></find></resources>
